# Using `bun` runtime: https://hub.docker.com/r/oven/bun/tags
# This is for development purposes only so you don't have to install bun locally

# Production build is generated by Vercel preview

FROM oven/bun:latest
WORKDIR /ecsess

COPY . /ecsess
RUN bun install

EXPOSE 5173

CMD ["bun", "run", "vite"]